classDiagram

class BaseModel {
+UUID id
+datetime created_at
+datetime updated_at

```
+save()
+update()
+delete()
```

}

class User {
+String first_name
+String last_name
+String email
+String password
+Boolean is_admin

```
+register()
+update_profile()
```

}

class Place {
+String title
+String description
+Float price
+Float latitude
+Float longitude

```
+add_amenity()
+remove_amenity()
```

}

class Review {
+Integer rating
+String comment

```
+edit_review()
```

}

class Amenity {
+String name
+String description

```
+update_amenity()
```

}

BaseModel <|-- User
BaseModel <|-- Place
BaseModel <|-- Review
BaseModel <|-- Amenity

User "1" --> "*" Place : owns

User "1" --> "*" Review : writes

Place "1" --> "*" Review : receives

Place "*" --> "*" Amenity : includes

