sequenceDiagram

    actor Client

    participant API as Place API
    participant Facade as HBnBFacade
    participant PlaceRepo as PlaceRepository
    participant DB as SQLite Database

    Client->>API: GET /places

    API->>Facade: get_all_places()

    Facade->>PlaceRepo: get_all()

    PlaceRepo->>DB: SELECT * FROM places

    DB-->>PlaceRepo: Place records

    PlaceRepo-->>Facade: List of Place objects

    Facade-->>API: List of Place objects

    API-->>Client: 200 OK (JSON list)
