sequenceDiagram

    actor Client

    participant API as User API
    participant Facade as HBnBFacade
    participant Repo as UserRepository
    participant DB as SQLite Database

    Client->>API: POST /users
    API->>API: Validate request

    API->>Facade: create_user(user_data)

    Facade->>Repo: get_user_by_email(email)

    alt Email already exists
        Repo-->>Facade: User found
        Facade-->>API: Error
        API-->>Client: 400 Email already exists

    else Email available
        Repo-->>Facade: None

        Facade->>Facade: hash_password()

        Facade->>Repo: add(user)

        Repo->>DB: INSERT user
        DB-->>Repo: Success

        Repo-->>Facade: User

        Facade-->>API: User

        API-->>Client: 201 Created
    end
